[package]
name = "backup-tools"
version = "1.3.3"
edition = "2021"
authors = ["Joel Dewey"]
description = "A Rust application to coordinate backups of applications hosted in my home Kubernetes cluster."
license = "GPL-3.0-only"
repository = "https://github.com/JoelDewey/backup-tools"
publish = false

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

[package.metadata.release]
sign-commit = true
sign-tag = true
tag-name = "v{{version}}"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
chrono = { version = "0.4.31", default-features = false, features = ["alloc", "std", "clock"] }
crossbeam = "0.8.2"
ctrlc = { version = "3.4.1", features = ["termination"] }
dotenvy = "0.15.7"
envy = "0.4.2"
rustls = "0.21.7"
rustls-native-certs = "0.6.3"
rustls-pemfile = "1.0.3"
serde = { version = "1.0.188", features = ["derive"] }
subprocess = "0.2.9"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
ureq = { version = "2.8.0", features = ["native-certs", "json", "tls"] }
url = "2.4.1"
