{{- if .Values.volume.destination.createPvc }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.volume.destination.claimName }}"
  annotations:
      {{- .Values.volume.destination.annotations | toYaml | nindent 4}}
  labels:
      {{- include "backup-tools.labels" . | nindent 4 }}
spec:
  {{- .Values.volume.destination.spec | toYaml | nindent 2 }}
{{- end }}