apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "backup-tools.jobRole" . }}
  labels:
    {{- include "backup-tools.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "patch"]