name: "Publish Helm Charts"

# Based off of https://dev.to/jamiemagee/how-to-host-your-helm-chart-repository-on-github-3kd

on:
  push:
    branches:
      - main
    paths:
      - "charts/backup-tools/**"

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'